version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root.123
      MYSQL_DATABASE: DVZ_ColegioUnion
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: DVZ_ColegioUnion
      DB_USER: root
      DB_PASSWORD: root.123
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge

healthcheck:
  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  interval: 5s
  timeout: 3s
  retries: 10

depends_on:
  mysql:
    condition: service_healthy

